<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Sonata\MediaBundle\Entity\BaseMedia as BaseMedia;

/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Media extends BaseMedia
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * @var string
     */
    protected $GPSLatitudeRef;

    /**
     * @var string
     */
    protected $GPSLatitude;

    /**
     * @var string
     */
    protected $GPSLongitudeRef;

    /**
     * @var string
     */
    protected $GPSLongitude;

    /**
     * @var string
     */
    protected $GPSAltitudeRef;

    /**
     * @var string
     */
    protected $GPSAltitude;

    /**
     * @var string
     */
    protected $GPSTimeStamp;

    /**
     * @var string
     */
    protected $GPSImgDirectionRef;

    /**
     * @var string
     */
    protected $GPSImgDirection;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set GPSLatitudeRef
     *
     * @param string $gPSLatitudeRef
     * @return Media
     */
    public function setGPSLatitudeRef($gPSLatitudeRef)
    {
        $this->GPSLatitudeRef = $gPSLatitudeRef;

        return $this;
    }

    /**
     * Get GPSLatitudeRef
     *
     * @return string 
     */
    public function getGPSLatitudeRef()
    {
        return $this->GPSLatitudeRef;
    }

    /**
     * Set GPSLatitude
     *
     * @param string $gPSLatitude
     * @return Media
     */
    public function setGPSLatitude($gPSLatitude)
    {
        $this->GPSLatitude = $gPSLatitude;

        return $this;
    }

    /**
     * Get GPSLatitude
     *
     * @return string 
     */
    public function getGPSLatitude()
    {
        return $this->GPSLatitude;
    }

    /**
     * Set GPSLongitudeRef
     *
     * @param string $gPSLongitudeRef
     * @return Media
     */
    public function setGPSLongitudeRef($gPSLongitudeRef)
    {
        $this->GPSLongitudeRef = $gPSLongitudeRef;

        return $this;
    }

    /**
     * Get GPSLongitudeRef
     *
     * @return string 
     */
    public function getGPSLongitudeRef()
    {
        return $this->GPSLongitudeRef;
    }

    /**
     * Set GPSLongitude
     *
     * @param string $gPSLongitude
     * @return Media
     */
    public function setGPSLongitude($gPSLongitude)
    {
        $this->GPSLongitude = $gPSLongitude;

        return $this;
    }

    /**
     * Get GPSLongitude
     *
     * @return string 
     */
    public function getGPSLongitude()
    {
        return $this->GPSLongitude;
    }

    /**
     * Set GPSAltitudeRef
     *
     * @param string $gPSAltitudeRef
     * @return Media
     */
    public function setGPSAltitudeRef($gPSAltitudeRef)
    {
        $this->GPSAltitudeRef = $gPSAltitudeRef;

        return $this;
    }

    /**
     * Get GPSAltitudeRef
     *
     * @return string 
     */
    public function getGPSAltitudeRef()
    {
        return $this->GPSAltitudeRef;
    }

    /**
     * Set GPSAltitude
     *
     * @param string $gPSAltitude
     * @return Media
     */
    public function setGPSAltitude($gPSAltitude)
    {
        $this->GPSAltitude = $gPSAltitude;

        return $this;
    }

    /**
     * Get GPSAltitude
     *
     * @return string 
     */
    public function getGPSAltitude()
    {
        return $this->GPSAltitude;
    }

    /**
     * Set GPSTimeStamp
     *
     * @param string $gPSTimeStamp
     * @return Media
     */
    public function setGPSTimeStamp($gPSTimeStamp)
    {
        $this->GPSTimeStamp = $gPSTimeStamp;

        return $this;
    }

    /**
     * Get GPSTimeStamp
     *
     * @return string 
     */
    public function getGPSTimeStamp()
    {
        return $this->GPSTimeStamp;
    }

    /**
     * Set GPSImgDirectionRef
     *
     * @param string $gPSImgDirectionRef
     * @return Media
     */
    public function setGPSImgDirectionRef($gPSImgDirectionRef)
    {
        $this->GPSImgDirectionRef = $gPSImgDirectionRef;

        return $this;
    }

    /**
     * Get GPSImgDirectionRef
     *
     * @return string 
     */
    public function getGPSImgDirectionRef()
    {
        return $this->GPSImgDirectionRef;
    }

    /**
     * Set GPSImgDirection
     *
     * @param string $gPSImgDirection
     * @return Media
     */
    public function setGPSImgDirection($gPSImgDirection)
    {
        $this->GPSImgDirection = $gPSImgDirection;

        return $this;
    }

    /**
     * Get GPSImgDirection
     *
     * @return string 
     */
    public function getGPSImgDirection()
    {
        return $this->GPSImgDirection;
    }
}
